require('log-timestamp');
const express = require('express');
const router = express.Router();
const client = require('../../elasticsearch/connection');



router.get('/similarNFTs', async function (req, res) {
    
   
    //======= Check that Elasticsearch is up and running =======\\ //only works for Elastic Cloud cluster
    pingElasticsearch = async () => {
        await client.ping(
            function(error,res) {
                if (error) {
                    console.error('elasticsearch cluster is down!');
                } else {
                    console.log('Elasticsearch Ready');
                }
            }
        );
    }

    similarNFTs = async () => {

        try {
                        
            const originalNFTData = await client.get({
                index: 'algoseaspirate', //replace with indexName/CollectionName 
                id: '20393'
              })


            console.log(' Generating elastisearch queries to return similar NFTs \n')  
            
         
            //bring this into .env /constants file later on
            //can also be autogenerated from http://172.18.0.2:9200/algoseaspirate/_mapping    http://eshost/index/mapping basically
            const metadataFields = //[ "Back Hand",  "Back Item",  "Background",  "Background Accent",  "Body",  "Face",  "Facial Hair",  "Footwear",  "Front Hand",  "Hat",  "Head",  "Hip Item",  "Left Arm",  "Necklace",  "Overcoat",  "Pants",  "Pet",  "Right Arm",  "Scenery",  "Shirt",  "Shirts",  "Tattoo",  
                              ["combat", "constitution", "luck", "plunder"];

            const integerFields = ["combat", "constitution", "luck", "plunder"];                   


            //build should query (OR query) to match various asset props here.
            //elasticsearch computes the similarity score accordingly depending on the no. of matches . https://www.elastic.co/guide/en/elasticsearch/reference/current/similarity.html
            const propertyQueries = [];
            metadataFields.forEach(function(property) {
                    propertyQueries.push({ "match": { [property] :  originalNFTData._source[property] }});                
                });


            //https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay   
            //https://stackoverflow.com/questions/37005785/how-to-find-the-nearest-closest-number-using-query-dsl-in-elasticsearch    
            //https://stackoverflow.com/questions/58046769/elasticsearch-find-closest-number-when-scoring-results?rq=1
            const functionScoreQueries = {}
            integerFields.forEach(function(property) {
                    functionScoreQueries[property] =  {
                                                                origin: originalNFTData._source[property],
                                                                scale: 1,
                                                                decay: 0.999
                                                             }; 
                });

            console.log(functionScoreQueries);

            const query = {                
                    "size" : 100, //we can control the no. of results from es with size here... 
                    "query": {
                        "function_score": {
                            "query": {
                                "bool": { 
                                    "should": propertyQueries
                                }
                            },
                            "functions" : [
                                {  //can be 'exp' for exponential or 'linear' 
                                "linear": functionScoreQueries
                                }
                            ]
                                
                        }
                    }
                }    
            
            console.log(JSON.stringify(query));   
            
            
            console.log(' Getting Similar NFTs from es query results \n')
            const result = await client.search({
                                index: originalNFTData._index,     
                                body: query
                            })
              
            
            //remove the top most result(originalNFT) from the elasticsearch result hits 
            let similarNFTs = result.hits.hits;
            similarNFTs.shift();
          
            res.json({  originalNFT : originalNFTData._source,
                        similarNFTs : similarNFTs  //descending with similarity score 
                    });            
            
        } catch (err) {
            console.log(err)
            res.json(err)
        };
        
    }
    
    pingElasticsearch()
    similarNFTs()     

});
 
module.exports = router;